// react/src/Header.tsx
import { FunctionComponent } from 'react';
import { useAppSelector } from './store/hooks';
import { selectMessageCount } from './store/messages/messages.state';

const MessageCountComponent: FunctionComponent<{ messageCount: number }> = ({messageCount}) => {
  return (
    <p>
      Vous avez {messageCount} messages
    </p>
  );
};


export const Header: FunctionComponent = () => {
  const messageCount = useAppSelector(selectMessageCount);
  return (
    <MessageCountComponent messageCount={messageCount}></MessageCountComponent>
  );
};

// src/app/header/header.component.ts
import {Component, OnInit} from '@angular/core';
import {EMPTY, Observable} from "rxjs";
import {selectMessageCount} from "../state";
import {Store} from "../store";

@Component({
  selector: 'app-header',
  templateUrl: './header.component.html',
  styleUrls: ['./header.component.css']
})
export class HeaderComponent implements OnInit {
  messageCount$: Observable<number> = EMPTY;

  constructor(private store: Store) {
  }

  ngOnInit(): void {
    this.messageCount$ = this.store.select(selectMessageCount);
  }

}

<p>Vous avez {{ messageCount }} messages</p>
